### ISSUE TITLE
Buen trabajo!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcas-s3-evaluacion-intermedia-Imoa1991#1]
Nos animamos a dar un paso mas y...?

1. Hacer un componente que pinte el ul, li y la card, y un componente solo para la card
2. los h1 de la card deberían ser h2, el img tiene que tener un alt="" y el li debe tener un key=""
3. Eliminar archivos que no usamos.

**Comment by Imoa1991** [comment]
Hola Carlos, 

No se a que te refieres con eliminar los archivos que no usamos...me puedes detallar esta parte un poco más.

Muchas gracias,
Irene

**Comment by oneeyedman** [comment]
Me refiero al registerServiceWorker.js, a los .css que no useamos, al logo.svg, y al archivo App.test.js

**Comment by oneeyedman** [comment]
Fíjate que en List solo tienes que meter el UL, el h1 no.
